Fixes: Build failure in GTK+ IC on older dbus-glib
RevBy: Michael Hasselmann
Use a gpointer instead of typedeffing the DBusGConnection,
as the struct has different names on older dbus-glib version,
leading to build failure:

/usr/include/dbus-1.0/dbus/dbus-glib.h:38:33: error: redefinition of typedef 'DBusGConnection'
meego-imcontext-dbus.h:28:33: note: previous declaration of 'DBusGConnection' was here

Introduced by 0901b5450be6afa109c1fcc3932d26aa233d4b1f

Full, original commit at 9de1e9a25052775d95a7fae0cb8f029e9578ed95 in maliit-framework